### ISSUE TITLE
Projects I'm creating now don't show up

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#242]
@brian-c I know you're all in the middle of fiddling with project fields. But while I can see projects I created yesterday and before, projects I've created today, I can't see.
Example that I **can** see:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Test25
Example that I **can't** see:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Test28

**Comment by brian-c** [comment]
@cam Could this be related to projects' default `beta` and `approved` values?

**Comment by camallen** [comment]
yep - updating

**Comment by camallen** [comment]
try again @mkosmala

**Comment by mkosmala** [comment]
Fixed!

**Comment by mkosmala** [comment]
@camallen All my project up until I commented last on this issue are now viewable. But new projects I make are not. Any way you can set this up so that newly created projects have the right defaults?

**Comment by vrooje** [comment]
seconded - I just ran into this as well

**Comment by edpaget** [comment]
For this and #247 it looks like the last staging deploy failed. I'm redeploying now, these should be fixed once that's done.

**Comment by edpaget** [comment]
This should be resolved.

**Comment by vrooje** [comment]
Not sure... I can now see the project in my Lab area but it's still not
showing up on the Projects page even though it's not private, and when I
click "view" from my Labs area I get the message "Error: Couldn't find
project brooke/Rescue Global Nepal 2015"

http://demo.zooniverse.org/panoptes-front-end/#/projects/brooke/Rescue
Global Nepal 2015 <-- also, spaces are back? I tried with "+" instead; nada.

**Comment by camallen** [comment]
@brian-c, @vrooje 's project had the approved state set to true and thus wasn't showing up the projects listing, `projects?beta=false&approved=false`.

The API defaults that field to false, are you setting this to true in the front end?

**Comment by camallen** [comment]
@vrooje you're project is now showing up and accessible (with spaces) http://demo.zooniverse.org/panoptes-front-end/#/projects/brooke/Rescue%20Global%20Nepal%202015

**Comment by vrooje** [comment]
Awesome! And the subjects are attached to the workflow too. Brilliant -
thanks :)

**Comment by brian-c** [comment]
@camallen those params were set for a few hours yesterday to work around projects not showing up otherwise.

**Comment by camallen** [comment]
got it, thanks.
