### ISSUE TITLE
Changing retirement limit throws error

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#246]
Have subject set defined, but when I try to set its retirement limit to 3 I get:

{"schema"=>"contains additional properties [\"retirement\"] outside of the schema when none are allowed"}

and the following error in the console:

https://panoptes-staging.zooniverse.org/api/subject_sets/1770 
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

**Comment by edpaget** [comment]
Ah damn. @brian-c this was a change I should have communicated. Retirement counts are now set on the workflow instead of the subject set.

**Comment by vrooje** [comment]
Huh. Was going to ask @brian-c about it but... despite all the above errors this now seems to be set at 3.

**Comment by vrooje** [comment]
Wait, no, now it's back to 15.

backing away very slowly now.

**Comment by camallen** [comment]
@vrooje that update failed in the backend but the frontend didn't reflect the failure. A reload would have shown 15 again.

**Comment by brian-c** [comment]
Sounds like it actually succeeded in the back end, just not in the right place. Does the subject_set model still have a `retirement` field perhaps?

**Comment by camallen** [comment]
`{"schema"=>"contains additional properties [\"retirement\"] outside of the schema when none are allowed"}` that's a failure on the submitted json.

Nope, it's on `workflow` now. https://github.com/edpaget/Panoptes/commit/5ca2a7eb7e20a465bda08edc4e82fe30d8e26954

**Comment by brian-c** [comment]
Oh sorry, I totally just misread the issue.

This should be fixed with that PR @vrooje.

**Comment by vrooje** [comment]
Okay. Still getting the error - but if subjects are served randomly it's
probably not absolutely critical as we can just stop early once we have
e.g. 5 apiece.

**Comment by brian-c** [comment]
The PR has not been merged yet.

**Comment by vrooje** [comment]
*as soon* as I hit send I figured that's what it was! :)
