### ISSUE TITLE
Some projects missing categories on new Zooniverse projects page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2585]
I noticed several projects that appear on the full project list but don't have a category associated with them -  Perhaps for @mrniaboc  or @alexbfree 

Cyclone Center doesn't show on the climate tab or any of the category tabs on the project list

Poppin Galaxy is not under Space and appears to not have an individual category

 Western Shield isn't listed under Nature or under any other category

Snapshots at Sea is not listed under Nature or any other category

Emigrant City also doesn't look to have a category I don't see it under History or Social Science

Science Gossip appears to be listed under almost every category (including space and physics) but not sure if that's because of the content of the articles or not, so maybe that's okay.

**Comment by aliburchard** [comment]
Thanks for catching this, Meg. I'm going to compile a quick "before you launch" checklist for Project Builder projects and add "categorise your project!" to that list.

**Comment by mschwamb** [comment]
@aliburchard I think most of those I listed launched before the new projects page so those project builders don't know they box exists and needs to be updated  or it is not accessible to the research team as the project is  not a project builder project like Emigrant City and Cyclone Center.

**Comment by CKrawczyk** [comment]
Re Science Gossip: it was placed in categories based on the contents of the articles.  

Most of the others were launched between the time @mrniaboc added tags to all existing projects and when the new projects page launched.

**Comment by alexbfree** [comment]
In order to set a discipline at the moment, only project collaborators can do it. However, once #2363 is fixed, Zooniverse admins will be able to set discipline tags and we'll be able to clean up these untagged projects in-house. I've created a PR which is ready for merge. https://github.com/zooniverse/Panoptes-Front-End/pull/2586

**Comment by alexbfree** [comment]
Looks like this'll be fixable by any admin once #2150 is fixed; or if someone gives me a list of correct/agreed disciplines (@grant ?) I can do it right now using code I developed for #2363.

**Comment by srallen** [comment]
Closing. Projects mentioned in this issue are fixed. Related issues #2150 and #2363 will remain open.

**Comment by mschwamb** [comment]
Cyclone Center is still not listed  under climate. Poppin' Galaxy was not added to Space. So this is not fixed. Reopening. 

![fireshot capture 24 - projects zooniverse_ - https___www zooniverse org_projects](https://cloud.githubusercontent.com/assets/753325/17339374/43a0bcba-5887-11e6-95b6-3c61538b08cc.png)

**Comment by mschwamb** [comment]
same thing for Emigrant City, it still has no category.

**Comment by srallen** [comment]
Ack, I thought those were fixed. Thank you.

**Comment by mschwamb** [comment]
Looks like Emigrant City, Snapshots at Sea, and Poppin Galaxy. are the last ones needed categories

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
