### ISSUE TITLE
If you already had a Zooniverse account and try out a new panoptes project you're not signed for the project's newsletters

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#470]
It looks like from the profile that I would need to manually check the panoptes projects  I was classifying on with my merged Zooniverse account on the preview site in order for me to get their newsletters.  Is that true? Because the check boxes were empty, it looks like to me that I'm not getting those projects' newsletters. 

screenshot below

![screen shot 2015-06-04 at 12 12 34 am](https://cloud.githubusercontent.com/assets/753325/7965234/c76e7f60-0a4e-11e5-9f35-e3c19cbca1e7.png)

**Comment by edpaget** [comment]
@brian-c @camallen looks like this is due to a 'feature' we added but forgot about. There are two email communication flags on the user model, a global one and project one. It looks like you only get signed up for project emails when you set the `project_email_communication` flag. 

It makes sense to me to have this. One could want Zooniverse emails, but not want to be automatically signed up for project specific emails. So let's set it to true for all new users by default and then add a checkbox somewhere in the interface for it.

**Comment by camallen** [comment]
@edpaget sounds good.

**Comment by mschwamb** [comment]
Question - if you were a classifier say on Galaxy Zoo before, would you be automatically signed up for a Galaxy Zoo newsletter if you had it checked in the previous version of the Zooniverse home profile?

**Comment by edpaget** [comment]
We're going to set up up as well.

**Comment by chrissnyder** [comment]
Believe this was addressed with a lot of the migration work that was done. @edpaget can you confirm?

**Comment by edpaget** [comment]
Yeah people should be subscribed by default now. The migration is still happening.

**Comment by chrissnyder** [comment]
Ok cool.

Closing this issue as the work is being done elsewhere and there isn't anything left to do on the front-end.
