### ISSUE TITLE
Missing items in translation file for PFE (not project-specific)

### ISSUE THREAD

**Issue by AnLand** [zooniverse/Panoptes-Front-End#5464]
Chimp&See re-launched in several additional languages. The project has been translated via the translation tool and additional (German, French) translations will be / have been provided for PFE. Other languages are already included. 

But several smaller items that would be useful for foreign language volunteers are not translated because **they are not part of the translation file**. Would it be possible to include them? These are minor points, but it includes reaching the profile settings, understanding communication (like messages and notifications), and of course the classification help "field guide".

I provide screenshots for better description (and because I can't find the code for these).

![field_guide](https://user-images.githubusercontent.com/7421089/61518729-905e3a00-aa0a-11e9-99d0-883bfa29dd5c.PNG)

![account_settings](https://user-images.githubusercontent.com/7421089/61518736-96541b00-aa0a-11e9-8652-446a2d0891a3.PNG)

![home_settings](https://user-images.githubusercontent.com/7421089/61518781-b08df900-aa0a-11e9-8321-95e861c8b24b.PNG)

![notification_messages](https://user-images.githubusercontent.com/7421089/61518791-b683da00-aa0a-11e9-953e-dee043b807c5.PNG)

![send_message](https://user-images.githubusercontent.com/7421089/61519481-4e35f800-aa0c-11e9-95db-05959c5dece8.PNG)

![notifications](https://user-images.githubusercontent.com/7421089/61519645-ac62db00-aa0c-11e9-8516-69f83b994703.PNG)

![collections](https://user-images.githubusercontent.com/7421089/61518750-9c49fc00-aa0a-11e9-9136-ed2fa9e46d19.PNG)

**Comment by yshish** [comment]
I would like to support Anja in this request. And also to ask to have the whole top nav bar (Projects / About / Get involved / Talk / Build a project / News) displayed as translated. I translated individual texts under pages 'About' and 'Get involved' into Czech but no one will get to read them since the buttons 'About' and 'Get involved' on the nav bar appear in English.

![ysh_Screenshot_2019-07-19_10-43-55](https://user-images.githubusercontent.com/7211888/61523785-55153880-aa15-11e9-97aa-d4e167034f05.png)

Also, the Zooniverse home page shows everything in English only and it is difficult for Czech volunteers to find how to get to their projects once they sign in to Zooniverse:
![ysh_Screenshot_2019-07-19_11-12-11](https://user-images.githubusercontent.com/7211888/61524224-4aa76e80-aa16-11e9-8896-35534eebdf9e.png)

For future re-design: It would be really nice to have a feature for filtering projects that are available in the chosen language. Since there are only few of them for each translation, it would take ages to check them one by one manually.

**Comment by AnLand** [comment]
The issues with translation discussed here are still the same and create problems in multilingual projects and for volunteers that want to learn more about Zooniverse. It should stay open - at least as a reminder to tackle those issues in the new front-end. Thank you!

**Comment by camallen** [comment]
Are these issues still occuring @AnLand ? i believe the research team could fix this by updating / changing the text of the impacted resources in the project builder.

**Comment by eatyourgreens** [comment]
@camallen I believe these are items that are missing from the JSON files in [`app/locales`](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/locales).

They are fixed, however, in [our new code](https://github.com/zooniverse/front-end-monorepo).

**Comment by camallen** [comment]
Marvellous - apologies for skim reading the issue.

**Comment by AnLand** [comment]
Yes, agreed, that is nothing the science teams can work on and it's still not fixed for Panoptes, unfortunately.

**Comment by AnLand** [comment]
Please keep open, it's still an issue. Thanks!

**Comment by yshish** [comment]
Also the labels for selected categories (displayed at the bottom of the classified image) appear in the original language when using translated version - this is confusing if you want to remove one of the selected categories and they are labeled in different language.
See the screenshot (labels at the bottom of the image say "cow" and "other species" while the categories in the task are labeled as "kráva" and "jiné zvíře").
![ysh_Screenshot_2021-05-15_11-04-20](https://user-images.githubusercontent.com/7211888/118354994-09c70500-b56e-11eb-80f3-e9d082d83f78.png)

**Comment by eatyourgreens** [comment]
@yshish those labels should be fixed now. Thanks for letting us know that they weren't being translated!

**Comment by yshish** [comment]
I can confirm they appear translated now. Thank you very much! :)
