### ISSUE TITLE
Updating a discussion via Moderator controls moves the discussion to a different board

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#6278]
## Expected behavior
In Chimp&See we work with lots of guides and lists we often update. In my case, I'm responsible for adding every new hashtag to the official List - this list is locked so no one could add comments there. When updating the List with a new hashtag I have to unlock the discussion first via the Moderator controls, edit the List, and then lock it again. After the changes I should be able to find the post on the same board as it was before the update.

## Current behavior
Usually it works as expected. But sometimes I cannot find the List on the Guides&Lists board where it belongs. Instead I find it on the 'Announcements' board. No one from the team moves it there though. Another moderator noticed the Moderator Controls sometimes(!) display an incorrect board in the drop down for 'Board' location - it seems to be displaying the 1st listed board instead of the current one, in our cases - 'Announcements'. She noticed that while updating a different discussion than me. It took me several attempts to duplicate this issue but I succeeded. So it seems it was me all the time who moved the post to another board while updating it. But as you see, not intentionally. I think this shouldn't happen. And if so then it should behave consistently, not randomly.

## Steps to replicate
Go to f.e. [this discussion](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278/899975) on the C&S Talk, open the Moderator Controls and look at the board location displayed in the drop down box. Compare it with the actual location of the discussion (displayed at the top of the Talk, just below the 'Chimp&See Talk' headline). Repeat until you get to see the 'Announcements' there instead of the 'Guides&Lists'.

## Additional information
It doesn't affect only my List but other posts on C&S Talk. And perhaps even other projects (didn't tested yet).
The other moderator uses a different OS/browser than me. I'm waiting for her reply. Will update with her details then.

- **Operating system:** Ubuntu, Linux
- **Browser:** Chrome 107

Screenshot (before taking the screenshot I spend some time away from my comp. The browser console didn't display any errors at first so I believe they are not related lol).
![ysh_Screenshot_2022-12-16_20-16-55](https://user-images.githubusercontent.com/7211888/208177136-ca9b74f2-bbd6-47ae-8d2f-f44ede4e6d84.png)

**Comment by yshish** [comment]
Here's what the other mod was using: 
>Chrome Version 108.0.5359.125 (Official Build) (64-Bit) (newest version) on a
Workstation with Windows 10 Pro, Version 21H2, 64bit processor but it happened also with older versions of browser and operating system. Actually, since we use the new platform.

**Comment by yshish** [comment]
Has anyone seen this report?

**Comment by eatyourgreens** [comment]
Thanks for reporting this @yshish.

That's definitely a bug in our code. It's hard to reproduce on a fast network connection but I'll leave this note to come back to later. This `select` menu will default to the first item if `discussion.board_id` isn't set when the page first loads eg. if the Panoptes Talk API is slow and it takes a while to fetch the board.
https://github.com/zooniverse/Panoptes-Front-End/blob/fbe426d0f5f3cc2d79a6b8e2b496032bff854f66/app/talk/discussion.cjsx#L356-L360

**Comment by eatyourgreens** [comment]
Changing `defaultValue` to `value` there should almost certainly fix it.

**Comment by yshish** [comment]
@eatyourgreens Thank you, Jim! (I was afraid it got forgotten over the Christmas. :))

**Comment by eatyourgreens** [comment]
Hi Zuzi! I think we figured out why this was happening, and it should be fixed now.

**Comment by yshish** [comment]
@eatyourgreens Awesome! Thank you :)

**Comment by yshish** [comment]
@eatyourgreens I have very bad news. It is still happening :( I've just received an email with screenshots from a colleague. Could you please look at it again? Will you need some more details?

**Comment by yshish** [comment]
Just opened the mod controls to update my discussion and noticed the incorrect board displayed there.
The browser console errors are different than the last time. In case it helps:
![ysh_Screenshot_2023-02-05_21-38-24](https://user-images.githubusercontent.com/7211888/216844702-5dc0bec3-2565-403e-bbd7-c77fb75fc257.png)

**Comment by yshish** [comment]
OK, tried to open the same discussion mod controls again in a new browser tab. The issue happened again but with no errors in the browser console!

**Comment by eatyourgreens** [comment]
Thanks! That’s useful to know. Those notifications errors aren’t related to the problem with the drop-down menu.

**Comment by yshish** [comment]
@eatyourgreens Just realized that it happens almost every single time when I work with the linked Chimp&See discussion but I have never experienced that when updating a discussion on the WesternShield Camera Watch using the same mod controls. Could it be project specific?

**Comment by yshish** [comment]
Possible steps to replicate:

1st way (getting a correct display of the Moderator controls): 
I've just tried getting to the C&S problematic discussion via a direct link in the Field Guide chapter called *# Official hashtag information* (here's the link: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278/899975) and when clicking on the Moderation controls, it displayed correctly. 

2nd way (getting the incorrect display):
Then I entered the discussion the way as usually - I went to the project Talk, clicked on the board called "[Guides & Lists](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278)" and then clicked on the discussion there. The Moderation controls loaded with the incorrect board! 

I repeated these steps several times (both ways of getting to the discussion) and it seems to be displayed incorrectly only when getting there via the Talk board (2nd way). It never happened via the Field guide direct link. 
Could anyone try it whether it is just me or whether it really depends on the way of how I get to the discussion? Thanks :)

**Comment by eatyourgreens** [comment]
Thanks @yshish, that’s really useful. I will try to take another look at this, this week.

**Comment by yshish** [comment]
Have you fixed it? :) Seems to be working today (4 times without any troubles so far).

**Comment by eatyourgreens** [comment]
@yshish I haven't made any changes, but glad to hear that it seems to be working now.

**Comment by yshish** [comment]
Sigh, it has just happened again :(

**Comment by eatyourgreens** [comment]
I'll take another look at this. I think you are right, that there is something about Chimp & See Talk is different from Talk for other projects.

**Comment by yshish** [comment]
Pretty please, could you look at this?
A new and surely related issue has just appeared on the Chimp&See Talk.

There was a discussion called [Resource Index](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278/1523228) under the Talk board called [Guides&Lists](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278).
One of the moderators couldn't find it there and asked where it is. I found it through the search box and linked to her question. Then I went through all the discussions under that Guides&Lists to realize, it is actually not there. But when you look at the top of the Resource Index, it says: [Chimp&See Talk](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk) > [Guides & Lists](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278) > Resource Index
instead of [Chimp&See Talk](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk) > [Announcements](https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2279) > Resource Index 
where it actually is due to the bug discussed above. 

(But when you go to the Announcements, where it was accidentally moved when someone updated it the last time, you will find it there, and it will show the address of the discussion correctly. Unlike when you find it through the search.)

See the discussion, click on the linked Resource index there to see the 'incorrect' address:
https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/talk/2278/3469932?page=1&scrollToLastComment=true

**Comment by eatyourgreens** [comment]
@goplayoutside3 is probably the best person to ask for help now.

**Comment by goplayoutside3** [comment]
Hi @yshish thank you for reporting the bug, and I doubly appreciate the documentation of it over time. Apologies for the delayed response, and I understand it's frustrating you keep encountering bugs on the Chimp&See Talk boards. 

At the moment I can file this report into Talk bugs, but we're almost always limited by available dev resources to fix things in the PFE codebase. While we are no longer actively developing features for this app, documenting through Issues is still helpful for future work when development focus can be shifted to Talk as a whole.

**Comment by yshish** [comment]
Thank you @goplayoutside3 for your response. So we can move the discussion where it belongs right away? (Don't want to destroy any 'evidence'. :))
